### ISSUE TITLE
Footer menus buttons-colors

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#17]
They all have wrongly colored text:

the Icons: #666
the texts: #9FA8A3

Link to Zeplin: zpl.io/2sfv2v

Pic:
![navi](https://cloud.githubusercontent.com/assets/13752872/10411269/ee54caf2-6f67-11e5-9dc3-faf6ba7eafa5.png)

**Comment by andeluvian** [comment]
This issue has been resolved
