### ISSUE TITLE
Close buttons should be BACK-buttons

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#18]
All of the "CLOSE"-buttons in the footer-menu should be "BACK"-buttons

Zeplin link: zpl.io/20FCaQ

The icon is .ion-ios-arrow-back

Pic:
![nav - back](https://cloud.githubusercontent.com/assets/13752872/10411294/8ff8e406-6f68-11e5-97dc-943ce457a24c.png)

**Comment by andeluvian** [comment]
This issue has been resolved
