### ISSUE TITLE
Wrong/Forced product picture size

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#23]
Pic
![lyttaantynytkuva](https://cloud.githubusercontent.com/assets/13752872/10412209/27b86938-6f87-11e5-9cd1-38ff547884f3.png)

Product pictures in the lists are forced to specific size so the aspect ratio is wrong.
This is super important to fix because the pictures are important as people are selling with images.

**Comment by andeluvian** [comment]
This has been fixed in a previous patch
