### ISSUE TITLE
Wishlist product bug

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#24]
Pic
![keskitysjatekstinkatkaisu](https://cloud.githubusercontent.com/assets/13752872/10412228/bd0fe236-6f87-11e5-8782-16d91948104e.png)

It seems that the product has a container which has border-radius.
The text cuts oddly.
The centering of everything is buggy.

So:
- container width image
- center the texts
- cut the description with CSS
- remove border-radius

**Comment by andeluvian** [comment]
This has been fixed in the latest patch
