### ISSUE TITLE
Cannot move from product-page to sellers-profile

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#25]
From here:
![notsellersprofile](https://cloud.githubusercontent.com/assets/13752872/10412261/e6eb1b7e-6f88-11e5-9007-a1ce477ccfa2.png)

By tapping the seller user should navigate to sellers profile-page.

**Comment by andeluvian** [comment]
This was a new feature added, this was missing in Swappler app Alpha that this app is based on, reassigning this from bugs to new task and new feature

**Comment by andeluvian** [comment]
This is now added but a side effect was created and a new bug has appeared, you can follow yourself and buy your own items

**Comment by andeluvian** [comment]
bug has been resolved
