### ISSUE TITLE
Profile-page background-image

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#26]
The profile background-image has to be adjusted a bit.

Now it looks like this.

Anttis profile-page
![screenshot_2015-10-11-15-12-55](https://cloud.githubusercontent.com/assets/13752872/10416746/7bcd4d14-702b-11e5-96d2-633b6b8f159e.png)

Lauris profile-page
![screenshot_2015-10-11-15-13-35](https://cloud.githubusercontent.com/assets/13752872/10416749/8ba3afbc-702b-11e5-9333-5d29214db8fa.png)

So the background pic should be bigger so it overflows out of the screen. And make it more blurry so it becomes more calm. The background-image is there just to give it color. No one has to see whats in it.

So:
- make it bigger, about 150%
- position: center center
- blur: about 25%-30%, so the white edges doesnt show.
- the "EDIT/FOLLOW/UNFOLLOW" must be positioned correctly. Half on top of the picture and half off.

**Comment by andeluvian** [comment]
The background image and the buttons have been adjusted and fixed
