### ISSUE TITLE
Weird notification in the activity feed?

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#27]
I have this in my activity feed:

![screenshot_2015-10-10-17-20-10](https://cloud.githubusercontent.com/assets/13752872/10416773/e8f97d8a-702c-11e5-909e-914583dcc5f6.png)

I dunno what it is?

**Comment by andeluvian** [comment]
most likely firebase issue probably notification node is missing , i will have a look from production and make a comparison

**Comment by andeluvian** [comment]
Firebase was missing msgBody node, the undefined is the event code for that message. once the msgBody node is created notification trigger can get the message for certain events. I have reported it to Nilesh and given instructions how to solve this problem.
