### ISSUE TITLE
No link in "People to follow"

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#30]
From the list "People to follow" should be able to navigate to every user on the list.

From here
![screenshot_2015-10-11-21-42-14](https://cloud.githubusercontent.com/assets/13752872/10422058/99ebd0c6-70bd-11e5-8113-111d83711c15.png)

**Comment by andeluvian** [comment]
This is a new feature added to the application. This was lacking documentation, current application is based on Swappler app Alpha and this page is a new feature that was added afterwards. Reassigning it to new Task and New feature

**Comment by andeluvian** [comment]
The people to follow page now goes to the user profile page
