### ISSUE TITLE
Swipable-pages/Tabs ui correction

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#31]
The current look
![chatlist](https://cloud.githubusercontent.com/assets/13752872/10422347/a8f43032-70c1-11e5-8a28-1b946fb73979.png)

The way it should be
![chatlist_tabs_buywish](https://cloud.githubusercontent.com/assets/13752872/10422358/db51a9ec-70c1-11e5-8157-b2dbefece800.png)
![chatlist_tabs_selling](https://cloud.githubusercontent.com/assets/13752872/10422357/db4e59cc-70c1-11e5-81cf-4027a74fd0ae.png)

- remove those round-indicators from the bottom
- views must be swipable and also user can tap the sub-headers/tabs to change tabs

**Comment by andeluvian** [comment]
Indicators have been removed and tabs are now swipable
