### ISSUE TITLE
Missing chat indicator from Menu-panel

### ISSUE THREAD

**Issue by SwapplerDEV** [SwapplerDEV/SwapplerApp#32]
There must be an indicator of "new messages" in the menu so its easy to see if theres new messages in any of the chats

Like so
![menu_white](https://cloud.githubusercontent.com/assets/13752872/10422384/5f73750c-70c2-11e5-975e-afef2b908159.png)

**Comment by andeluvian** [comment]
This is a new feature, it exists in the documentation, but current app is based on Swappler App Alpha, documentation was missing when these features were being added, so this is not a bug just a new task and a new feature
