### ISSUE TITLE
Infinite loading on discover page upon starting the app.

### ISSUE THREAD

**Issue by nileshlg2003** [SwapplerDEV/SwapplerApp#6]
If the there are No items/products near by your location then app will keep searching for items and Ionic Loader will keep rotating preventing any interaction with rest of the app.

**Comment by nileshlg2003** [comment]
1. There should be timer for loader on this particular page so that loader should stop after 10 seconds and Display message that "No items/products around". Such a way user can at-least navigate around or use rest of the app.

**Comment by nileshlg2003** [comment]
As a temporary solution, removed the Ionic Loader altogether.Must Revisit this issue soon.

**Comment by andeluvian** [comment]
This has been fixed in the new version of the app, this issue can be closed
