### ISSUE TITLE
Infinite loop after logon

### ISSUE THREAD

**Issue by andeluvian** [SwapplerDEV/SwapplerApp#8]
After logon the loader is in a infinite loop, causing problems after DB cleanup.

Same problem exists in test db, only for IOS at the moment, iphone is idle on main screen and the the loader starts loops forever, even if it has products on the main screen after 5 minute idle it will start infinite loop.

****Workaround in test is to boot the iphone*****

**Comment by nileshlg2003** [comment]
refer #6

**Comment by andeluvian** [comment]
This has been fixed with a new geolocation plugin, also added a failsafe message for users if the user has disabled location service, a popup message will appear indicating to turn on the location servoce for the app to work properly.
