### ISSUE TITLE
No Location service - > Items appear in USA

### ISSUE THREAD

**Issue by andeluvian** [SwapplerDEV/SwapplerApp#9]
If mobile device has disabled location service default location is 

    $cordovaGeolocation
                .getCurrentPosition()
                .then(function (position) {
                    geoLocation.setGeolocation(position.coords.latitude, position.coords.longitude)
                }, function (err) {
                    geoLocation.setGeolocation(37.38, -122.09)
                });

            // begin a watch
            var options = {
                frequency: 1000,
                timeout: 3000,
                enableHighAccuracy: true
            };

            var watch = $cordovaGeolocation.watchPosition(options);
            watch.then(function () { /* Not  used */
                },
                function (err) {
                    geoLocation.setGeolocation(37.38, -122.09)
                }, function (position) {
                    geoLocation.setGeolocation(position.coords.latitude, position.coords.longitude)
                });
  });
})

Have to set the default location to users previous logon location, investigation is required

**Comment by andeluvian** [comment]
Adding a button to the settings like "my current position" saving that in Firebase as users default location //sugestion

**Comment by nileshlg2003** [comment]
yes but, we are setting location is app.js/.run({})
so by this time user is not even in authenticated to use his ID to Retrieve his location from firebase.

**Comment by nileshlg2003** [comment]
can me move this code to one of the services? that way we can retrieve his location anytime we want.

**Comment by andeluvian** [comment]
Yes it is possible we will have to map the app now into small pieces first to see what to improve and how, but anything at the moment is possible, even the data of current postion can be stored locally and be retrieved , dunno yet but we are putting up ideas as we probe the code

**Comment by andeluvian** [comment]
This error is fixed now with the new geolocation service and plugin.
